# Default values for openebs-withlvm-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
config:
  platform: azure

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: agentpool
              operator: In
              values: ["logscale"]
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
